# Rainb0w Lite config file
VERSIONCODE=1.8

[CERT]
# This domain must be an accessible and well-known domain
# also any active probing will be redirected there.
FAKE_SNI = ""

[XRAY]
IS_ENABLED = false
PORT = 443  # Also available on 8443
PRIVATE_KEY = ""
PUBLIC_KEY = ""

[HYSTERIA]
IS_ENABLED = false
PORT = 8443 # 443 when obfs is blank
ALPN = ""
OBFS = ""

[MTPROTO]
IS_ENABLED = false
PORT = 993
EXTRA_PORT = 0
AD_TAG = ""

[BLOCKY]
IS_ENABLED = false
PORT = 53
