# Rainb0w Lite config file
VERSIONCODE=1.5

[CERT]
# This domain must be an accessible and well-known domain
# also any active probing will be redirected there.
FAKE_SNI = ""

[XRAY]
IS_ENABLED = false
PORT = 443
PRIVATE_KEY = ""
PUBLIC_KEY = ""

[HYSTERIA]
IS_ENABLED = false
PORT = 8443
ALPN = ""
OBFS = ""

[MTPROTO]
IS_ENABLED = false
PORT = 9443
